name: Continuous Integration

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    name: Build for Emscripten
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Install dependencies (potential)
        run: |
          sudo apt-get update
          sudo apt-get install \
            libsdl2-dev \
            libsdl2-mixer-dev \
            libsdl2-net-dev \
            libpng-dev \
            libsamplerate0-dev \
            libfluidsynth-dev

      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v14

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure
        run: emconfigure ./autogen.sh

      - name: Build
        run: export ROOTPROJDIR="$PWD"; emmake make -j4 LDFLAGS="--preload-file \"$ROOTPROJDIR/wads/doom1.wad\"@doom1.wad"

      - name: Upload engine (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: emscripten-build
          path: |
            ./src/chocolate-doom.html
            ./src/chocolate-doom.wasm
            ./src/chocolate-doom.js
