name: Continuous Integration

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    name: Build for Emscripten
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Install dependencies (potential)
        run: |
          sudo apt-get update
          sudo apt-get install \
            libsdl2-dev \
            libsdl2-mixer-dev \
            libsdl2-net-dev \
            libpng-dev \
            libsamplerate0-dev \
            libfluidsynth-dev

      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v14

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure
        run: emconfigure ./autogen.sh

      - name: Build
        run: export ROOTPROJDIR="$PWD"; emmake make -j4 LDFLAGS="--preload-file \"$ROOTPROJDIR/wads/doom1.wad\"@doom1.wad"

      - name: Upload engine (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: emscripten-build
          path: |
            ./src/chocolate-doom.html
            ./src/chocolate-doom.wasm
            ./src/chocolate-doom.js
  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ghpages
    - name: Setup Node & NPM
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        path: ./
        pattern: emscripten-build
        merge-multiple: true
    - name: Uglify JS for faster runtime (probably)
      run: |
          npm install uglify-js -g
          uglifyjs chocolate_doom.js -c > chocolate_doom.js.min
          rm chocolate_doom.js
          mv chocolate_doom.js.min chocolate_doom.js
    - name: Push to GH Pages
      run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update GH Pages as per master branch"
          git push
